using System.Collections.Generic;

namespace WordAddIn1
{
    public partial class RibbonMJS
    {
        private static string BuildIdxHtmlTemplate(string docTitle, string docid, Dictionary<string, string> mergeScript)
        {
            string idxHtmlTemplate = "";
            idxHtmlTemplate += @"<?xml version=""1.0"" encoding=""utf-8"" ?>" + "\n";
            idxHtmlTemplate += @"<!DOCTYPE HTML>" + "\n";
            idxHtmlTemplate += @"<html>" + "\n";
            idxHtmlTemplate += @"<head>" + "\n";
            idxHtmlTemplate += @" <meta http-equiv=""X-UA-Compatible"" content=""IE=edge"" />" + "\n";
            idxHtmlTemplate += @"<meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"" />" + "\n";
            idxHtmlTemplate += @"<meta name=""viewport"" content=""width=device-width, initial-scale=1, maximum-scale=3, user-scalable=yes"" />" + "\n";
            idxHtmlTemplate += @"<meta name=""generator"" content=""Adobe Framemaker 2017"" />" + "\n";
            idxHtmlTemplate += @"<title>" + docTitle + "</title>" + "\n";
            idxHtmlTemplate += @"<link rel=""StyleSheet"" href=""template/Azure_Blue01/layout.css"" type=""text/css"" />" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/rh.min.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/common.min.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/layout.min.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/constants.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/projectdata.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/utils.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/mhutils.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/mhlang.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/mhver.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/settings.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/XmlJsReader.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/loadscreen.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/loadcsh.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/loadparentdata.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/loadprojdata.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/showhidecontrols.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/pageloader.js""></script>" + "\n";
            idxHtmlTemplate += @"<link rel=""stylesheet"" type=""text/css"" href=""template/styles/widgets.min.css"">" + "\n";
            idxHtmlTemplate += @"<link rel=""stylesheet"" type=""text/css"" href=""template/styles/layoutfix.min.css"">" + "\n";
            idxHtmlTemplate += @"<link rel=""stylesheet"" type=""text/css"" href=""template/styles/layout.min.css"">" + "\n";
            idxHtmlTemplate += @"<link rel=""stylesheet"" type=""text/css"" href=""template/styles/font.css"">" + "\n";
            idxHtmlTemplate += @"<link rel=""stylesheet"" type=""text/css"" href=""template/styles/resp.css"">" + "\n";
            idxHtmlTemplate += @"<link rel=""stylesheet"" type=""text/css"" href=""template/styles/pdf.css"" >" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/mhfhost.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""template/scripts/search.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""promise-6.1.0.min.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""jquery-3.1.0.min.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""html2canvas.min.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""jspdf.min.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""jquery.cookie.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""resp.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""fontchange.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""pdf.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" src=""search.js""></script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" >" + "\n";
            idxHtmlTemplate += @"gTopicFrameName = ""rh_default_topic_frame_name"";" + "\n";
            idxHtmlTemplate += @"gDefaultTopic = ""#" + docid + @"00000.html"";" + "\n";
            idxHtmlTemplate += @"</script>" + "\n";
            idxHtmlTemplate += @"<script type=""text/javascript"" >" + "\n";
            idxHtmlTemplate += @"gRootRelPath = ""."";" + "\n";
            idxHtmlTemplate += @"gCommonRootRelPath = ""."";" + "\n";
            idxHtmlTemplate += @"mergePage = {" + "\n";
            foreach (var item in mergeScript)
            {
                idxHtmlTemplate += item.Value.Split(new char[] { '♯' })[0] + ":'" + item.Key.Split(new char[] { '♯' })[0] + "',";
            }
            idxHtmlTemplate += @"};" + "\n";
            idxHtmlTemplate += @"function findFirstPageInMerge(page) {" + "\n";
            idxHtmlTemplate += @"    var found = false;" + "\n";
            idxHtmlTemplate += @"    for (let key in mergePage) {" + "\n";
            idxHtmlTemplate += @"        if (mergePage[key] == page) {" + "\n";
            idxHtmlTemplate += @"            found = true;" + "\n";
            idxHtmlTemplate += @"            return findFirstPageInMerge(key);" + "\n";
            idxHtmlTemplate += @"            break;" + "\n";
            idxHtmlTemplate += @"        }" + "\n";
            idxHtmlTemplate += @"    }" + "\n";
            idxHtmlTemplate += @"    if (!found) {" + "\n";
            idxHtmlTemplate += @"        return page;" + "\n";
            idxHtmlTemplate += @"    }" + "\n";
            idxHtmlTemplate += @"}" + "\n";
            idxHtmlTemplate += @"$(function() {" + "\n";
            idxHtmlTemplate += @"    updateLink();" + "\n";
            idxHtmlTemplate += @"});" + "\n";
            idxHtmlTemplate += @"function updateLink() {" + "\n";
            idxHtmlTemplate += @"    $(""ul.toc a, .wSearchResultItemsBlock a.nolink"").each(function() {" + "\n";
            idxHtmlTemplate += @"        var href = $(this).attr(""href"");" + "\n";
            idxHtmlTemplate += @"        if (href.match(""([A-Z]{3}[0-9]{5}[.]html)[?]rhtocid=.+[#]([A-Z]{3}[0-9]{5})"")) {" + "\n";
            idxHtmlTemplate += @"            var rex = /([A-Z]{3}[0-9]{5}[.]html)[?]rhtocid=.+[#]([A-Z]{3}[0-9]{5})/g;" + "\n";
            idxHtmlTemplate += @"            var arr = rex.exec(href);" + "\n";
            idxHtmlTemplate += @"            $(this).attr(""href"", findFirstPageInMerge(arr[1].replace("".html"","""")) + "".html#"" + arr[2]);" + "\n";
            idxHtmlTemplate += @"        }else if($(this).hasClass(""nolink"")){" + "\n";
            idxHtmlTemplate += @"            if(!$(this).hasClass(""changed"")){" + "\n";
            idxHtmlTemplate += @"                var rex = /([A-Z]{3}[0-9]{5}[.]html)/g;" + "\n";
            idxHtmlTemplate += @"                var arr = rex.exec(href);" + "\n";
            idxHtmlTemplate += @"                $(this).addClass(""changed"");" + "\n";
            idxHtmlTemplate += @"                var from = findFirstPageInMerge(arr[1].replace("".html"",""""));" + "\n";
            idxHtmlTemplate += @"                var to=arr[1].replace("".html"","""");" + "\n";
            idxHtmlTemplate += @"                if(from==to){" + "\n";
            idxHtmlTemplate += @"                    to="""";" + "\n";
            idxHtmlTemplate += @"                }" + "\n";
            idxHtmlTemplate += @"                $(this).attr(""href"", from + "".html#"" + to);" + "\n";
            idxHtmlTemplate += @"            }" + "\n";
            idxHtmlTemplate += @"        }" + "\n";
            idxHtmlTemplate += @"    });" + "\n";
            idxHtmlTemplate += @"    setTimeout(function() {" + "\n";
            idxHtmlTemplate += @"        updateLink();" + "\n";
            idxHtmlTemplate += @"    }, 200);" + "\n";
            idxHtmlTemplate += @"}" + "\n";
            idxHtmlTemplate += @"</script>" + "\n";
            idxHtmlTemplate += @"</head>" + "\n";
            idxHtmlTemplate += @"<body class=""hide-children loading"" data-rhwidget=""Basic"" data-class=""media-desktop: KEY_SCREEN_DESKTOP; media-landscape: KEY_SCREEN_TABLET; media-mobile: KEY_SCREEN_PHONE; ios: KEY_SCREEN_IOS"" data-controller=""ModernLayoutController: mc; JsLoadingController"" data-attr=""dir:KEY_DIR"">" + "\n";
            //idxHtmlTemplate += @"<script type=""text/javascript"" src=""ehlpdhtm.js""></script>" + "\n";
            idxHtmlTemplate += @"<!-- Extra mobile header with special functions -->" + "\n";
            idxHtmlTemplate += @"<div class=""mobilespecialfunctions"" data-class=""sidebar-opened: $mc.isSidebarTab(@KEY_ACTIVE_TAB); mobile-header-visible: @.l.mobile_header_visible; searchpage-mode: @KEY_ACTIVE_TAB == 'fts'"">" + "\n";
            idxHtmlTemplate += @"   <a class=""menubutton"" data-attr=""href: '#'; title:@KEY_LNG.NavTip;"" data-click=""$mc.toggleSideBar()"" data-if=""@.l.mobile_menu_enabled === true""></a> " + "\n";
            idxHtmlTemplate += @"   <a class=""fts"" data-attr=""href: '#'; title:@KEY_LNG.SearchTitle;"" data-click=""$mc.toggleActiveTab('fts')"">&#160;</a>" + "\n";
            idxHtmlTemplate += @"   <a class=""filter"" data-attr=""href: '#'; title:@KEY_LNG.Filter"" data-if=""KEY_FEATURE.filter"" data-class=""filter-applied: @.l.tag_expression.length""  data-click=""$mc.toggleActiveTab('filter')"">&#160;</a>" + "\n";
            idxHtmlTemplate += @"   <div class=""brs-holder"">" + "\n";
            idxHtmlTemplate += @"     <div class=""brs_previous"" data-if=""@active_content != 'search' && @KEY_SEARCH_LOCATION == 'content'"" data-attr=""title:@KEY_LNG.Prev""><a id=""browseSeqBackMobile"" class=""wBSBackButton"" data-rhwidget=""Basic"" data-attr=""href:.l.brsBack"" data-css=""visibility: @.l.brsBack?'visible':'hidden'"">&nbsp;</a>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"     <div class=""brs_next"" data-if=""@active_content != 'search' && @KEY_SEARCH_LOCATION == 'content'"" data-attr=""title:@KEY_LNG.Next""><a id=""browseSeqNextMobile"" class=""wBSNextButton"" data-rhwidget=""Basic"" data-attr=""href:.l.brsNext"" data-css=""visibility: @.l.brsNext?'visible':'hidden'"">&nbsp;</a>" + "\n";
            idxHtmlTemplate += @"</div>   " + "\n";
            idxHtmlTemplate += @"   </div>  " + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Function bar with TOC/IDS/GLO/FILTER/FTS buttons -->" + "\n";
            idxHtmlTemplate += @"<div class=""functionbar"" data-css=""width: sidebar_width | screen: 'desktop'"" data-class=""sidebar-opened: $mc.isSidebarTab(@KEY_ACTIVE_TAB); desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; mobile-header-visible: @.l.mobile_header_visible"">" + "\n";
            idxHtmlTemplate += @"   <div class=""nav"">" + "\n";
            idxHtmlTemplate += @"       <a class=""toc"" data-if=""KEY_FEATURE.toc"" data-class=""active: @KEY_ACTIVE_TAB == 'toc'"" data-click=""$mc.toggleActiveTab('toc')"" data-attr=""title:@KEY_LNG.TableOfContents; href: '#'"">&#160;</a>" + "\n";
            idxHtmlTemplate += @"       <a class=""filter"" data-if=""KEY_FEATURE.filter"" data-class=""active: @KEY_ACTIVE_TAB == 'filter'; filter-applied: @.l.tag_expression.length""  data-click=""$mc.toggleActiveTab('filter')"" data-attr=""title:@KEY_LNG.Filter; href: '#'"">&#160;</a>" + "\n";
            idxHtmlTemplate += @"       <a class=""fts"" data-if=""@KEY_SEARCH_LOCATION == 'tabbar'"" data-class=""active: @KEY_ACTIVE_TAB == 'fts'; search-sidebar: @KEY_SEARCH_LOCATION == 'tabbar'"" data-click=""$mc.toggleActiveTab('fts')"" data-attr=""title:@KEY_LNG.SearchTitle; href: '#'"">&#160;</a>" + "\n";
            idxHtmlTemplate += @"   </div>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Table of contents -->" + "\n";
            idxHtmlTemplate += @"<div class=""toc-holder left-pane"" data-css=""width: sidebar_width | screen: 'desktop'"" data-class=""desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; search-sidebar: @KEY_SEARCH_LOCATION == 'tabbar'; search-content: @KEY_SEARCH_LOCATION == 'content'; layout-visible: @KEY_ACTIVE_TAB == 'toc'; drill-down: KEY_TOC_DRILL_DOWN; mobile-header-visible: @.l.mobile_header_visible; loading: !@EVT_TOC_LOADED"">" + "\n";
            idxHtmlTemplate += @"   <ul class=""toc"" data-rhwidget=""List: .p.toc"" data-controller=""TocController: toc"" data-click=""$toc.onClick(event)"">" + "\n";
            idxHtmlTemplate += @"       <li data-rif=""item.type === 'item' || item.type === 'remoteitem'"" data-i-class=""$toc.class(item)"" data-class=""inactive: @bookid != '#{@pid}'"" data-childorder=""#{childOrder}"" data-rhtags=""#{$toc.tags(item)}"" data-itemid=""#{@id}"">" + "\n";
            idxHtmlTemplate += @"           <a data-itext=""item.name"" data-i-href=""$toc.url(item, '#{@id}')""></a>" + "\n";
            idxHtmlTemplate += @"       </li>" + "\n";
            idxHtmlTemplate += @"       <li class=""book"" data-rif=""item.type === 'book'"" data-class=""active: @bookid == '#{@id}'; inactive: @bookid != '#{@pid}' &amp;&amp; @bookid != '#{@id}'"" data-childorder=""#{childOrder}""" + "\n";
            idxHtmlTemplate += @"           data-itemkey=""#{$toc.key(item.absRef, item.key)}"" data-itemid=""#{@id}"" data-itemlevel=""#{@level}"" data-rhtags=""#{$toc.tags(item)}"">" + "\n";
            idxHtmlTemplate += @"           <a data-itext=""item.name"" data-i-href=""$toc.url(item, '#{@id}')""></a>" + "\n";
            idxHtmlTemplate += @"       </li>" + "\n";
            idxHtmlTemplate += @"       <li class=""child max-height-transition"" data-rif=""item.key"" data-class=""show: @show_child#{@id}"" data-childorder=""#{childOrder}"">" + "\n";
            idxHtmlTemplate += @"         <ul class=""child"" data-child=""$toc.key(item.absRef, item.key)""></ul>" + "\n";
            idxHtmlTemplate += @"       </li>" + "\n";
            idxHtmlTemplate += @"   </ul>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Index -->" + "\n";
            idxHtmlTemplate += @"<div class=""idx-holder left-pane"" data-css=""width: sidebar_width | screen: 'desktop'"" data-class=""desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; layout-visible: @KEY_ACTIVE_TAB == 'idx'; mobile-header-visible: @.l.mobile_header_visible"" data-scroll=""@.l.load_more_index(true) | debounce: 50, delta: 100"">" + "\n";
            idxHtmlTemplate += @"   <div id=""idx"" class=""Index"">" + "\n";
            idxHtmlTemplate += @"       <input class=""IdxFilter"" data-attr=""placeholder:@KEY_LNG.IndexFilterKewords"" type=""text"" data-keyup=""@.l.idxfilter(node.value)"" />" + "\n";
            idxHtmlTemplate += @"        <ul class=""index-list"" data-rhwidget=""List: key: PROJECT_INDEX_DATA, , filter: $ic.showItem(item.name), spliton: index % 60 == 59"" data-config=""loadmore: '.l.load_more_index'"" data-controller=""IndexController: ic""> " + "\n";
            idxHtmlTemplate += @"           <li class=""treeitem IndexAlphabet"" data-rif=""$ic.showCategory(item.name, this.path.length)"" data-itemlevel=""#{@level}""> " + "\n";
            idxHtmlTemplate += @"             <span class=""IndexAlphabetText"" data-itext=""$ic.alphaText(item.name)""></span> " + "\n";
            idxHtmlTemplate += @"           </li>" + "\n";
            idxHtmlTemplate += @"           <li class=""treeitem IndexKeyword"" data-i-data-rhtags=""item['data-rhtags']"">" + "\n";
            idxHtmlTemplate += @"               <a data-rif=""item.topics &amp;&amp; item.topics.length == 1"" class=""nolink IndexKeywordText"" data-i-href=""item.topics[0].url"" data-itext=""item.name""> " + "\n";
            idxHtmlTemplate += @"               </a> " + "\n";
            idxHtmlTemplate += @"               <span class=""IndexKeywordText IndexKeyword unselectable"" data-itext=""item.name"" data-rif=""item.topics &amp;&amp; item.topics.length != 1"" data-i-title=""item.name"" data-click=""@show.#{@id}(!@show.#{@id})""></span> " + "\n";
            idxHtmlTemplate += @"           <ul data-if=""@show.#{@id}"" style=""list-style-type: none;"">" + "\n";
            idxHtmlTemplate += @"            <li data-repeat=""i, topic:#{@itemkey}.topics"" data-rif=""item.topics &amp;&amp; item.topics.length > 1"" class=""IndexChildBlock IndexKeyword""> " + "\n";
            idxHtmlTemplate += @"             <a class=""nolink IndexLink IndexLinkText"" data-i-href=""$topic.url"" data-i-data-rhtags=""$topic['data-rhtags']"" data-itext=""$topic.name"" data-i-title=""$topic.name""> " + "\n";
            idxHtmlTemplate += @"             </a> " + "\n";
            idxHtmlTemplate += @"            </li>" + "\n";
            idxHtmlTemplate += @"           </ul>" + "\n";
            idxHtmlTemplate += @"            <div class=""IndexChildBlock"" data-rif=""item['keys']""> " + "\n";
            idxHtmlTemplate += @"             <ul class=""child"" data-child=""#{@itemkey}.keys"" style=""list-style-type: none;""></ul> " + "\n";
            idxHtmlTemplate += @"            </div>" + "\n";
            idxHtmlTemplate += @"          </li> " + "\n";
            idxHtmlTemplate += @"        </ul>" + "\n";
            idxHtmlTemplate += @"   </div>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Glossary -->" + "\n";
            idxHtmlTemplate += @"<div class=""glo-holder left-pane"" data-css=""width: sidebar_width | screen: 'desktop'"" data-class=""desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; layout-visible: @KEY_ACTIVE_TAB == 'glo'; mobile-header-visible: @.l.mobile_header_visible"">" + "\n";
            idxHtmlTemplate += @"   <div id=""glo"" class=""Glossary"" data-controller=""GlossaryController: gc"">" + "\n";
            idxHtmlTemplate += @"       <input class=""GloFilter"" data-attr=""placeholder:@KEY_LNG.GlossaryFilterTerms"" type=""text"" data-keyup=""$gc.filterGlo(node.value)""/>" + "\n";
            idxHtmlTemplate += @"           <ul style=""list-style: none;""> " + "\n";
            idxHtmlTemplate += @"               <div data-repeat=""i, glossary: PROJECT_GLOSSARY_DATA""> " + "\n";
            idxHtmlTemplate += @"                   <li class=""treeitem GloAlphabet"" data-rif=""!$gc.exists($glossary.name)&amp;&amp;!$gc.isFiltered($glossary.name)""> " + "\n";
            idxHtmlTemplate += @"                       <span class=""GloAlphabetText"" data-itext=""$gc.alphaText($glossary.name)""></span>" + "\n";
            idxHtmlTemplate += @"                   </li>" + "\n";
            idxHtmlTemplate += @"                   <li class=""treeitem"" data-rif=""!$gc.isFiltered($glossary.name)""> " + "\n";
            idxHtmlTemplate += @"                       <div class=""GlossTerm unselectable"" data-type=""11"" data-i-title=""$glossary.name"" data-term=""$glossary.name"" data-click=""@show.#{@index}(!@show.#{@index})""> " + "\n";
            idxHtmlTemplate += @"                           <span class=""GlossaryTermText"" data-itext=""$glossary.name""></span>" + "\n";
            idxHtmlTemplate += @"                       </div> " + "\n";
            idxHtmlTemplate += @"                       <div class=""GlossDefinition unselectable"" data-type=""12"" data-if=""@show.#{@index}""> " + "\n";
            idxHtmlTemplate += @"                           <span class=""GlossDefinitionText"" data-itext=""$glossary.value""></span> " + "\n";
            idxHtmlTemplate += @"                       </div> " + "\n";
            idxHtmlTemplate += @"                   </li> " + "\n";
            idxHtmlTemplate += @"               </div> " + "\n";
            idxHtmlTemplate += @"           </ul> " + "\n";
            idxHtmlTemplate += @"   </div>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Filter -->" + "\n";
            idxHtmlTemplate += @"<div class=""filter-holder left-pane"" data-css=""width: sidebar_width | screen: 'desktop'"" data-class=""sidebar-opened: $mc.isSidebarTab(@KEY_ACTIVE_TAB); desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; layout-visible: @KEY_ACTIVE_TAB == 'filter'; mobile-header-visible: @.l.mobile_header_visible; loading: !@KEY_MERGED_FILTER_KEY"">" + "\n";
            idxHtmlTemplate += @"   <div class=""mobile-filter-heading"" data-if=""KEY_SCREEN_PHONE"">" + "\n";
            idxHtmlTemplate += @"       <a class=""mobile_back"" data-click=""$mc.filterDone()"" data-attr=""title:@KEY_LNG.ApplyTip""></a>" + "\n";
            idxHtmlTemplate += @"       <div class=""page-title"" data-text=""KEY_PROJECT_FILTER_CAPTION""></div>" + "\n";
            idxHtmlTemplate += @"       <a class=""reset-button"" data-attr=""href: '#'; title: @KEY_LNG.Reset"" data-click=""$mc.setDefaultTagStates()"" data-class=""layout-visible: $mc.isTagStatesChanged(@KEY_TAG_EXPRESSION)""></a>" + "\n";
            idxHtmlTemplate += @"   </div>" + "\n";
            idxHtmlTemplate += @"   <p class=""filter-title"" data-if=""(@KEY_SCREEN_TABLET || @KEY_SCREEN_DESKTOP) &amp;&amp; @KEY_MERGED_FILTER_KEY"" data-text=""KEY_PROJECT_FILTER_CAPTION""></p>" + "\n";
            idxHtmlTemplate += @"   <a class=""reset-button"" data-attr=""href: '#'; title: @KEY_LNG.Reset"" data-click=""$mc.setDefaultTagStates()"" data-class=""layout-visible: $mc.isTagStatesChanged(@KEY_TAG_EXPRESSION)""></a>" + "\n";
            idxHtmlTemplate += @"   <ul class=""wFltOpts"" data-rhwidget=""List:KEY_MERGED_FILTER_KEY"" data-controller=""FilterController: fc"" data-click=""$fc.click(event)""" + "\n";
            idxHtmlTemplate += @"   data-class=""radio: @KEY_PROJECT_FILTER_TYPE == 'radio'; checkbox: @KEY_PROJECT_FILTER_TYPE == 'checkbox'"">" + "\n";
            idxHtmlTemplate += @"       <li data-i-class=""$fc.class(item)"" data-itemkey=""#{@path}"" data-itemvalue=""#{name}"">" + "\n";
            idxHtmlTemplate += @"         <input data-rif=""$fc.inputType(item) == 'checkbox'"" data-i-id=""'filter#{@id}'"" type=""checkbox"" data-i-value=""#{@index}""/>" + "\n";
            idxHtmlTemplate += @"         <input data-rif=""$fc.inputType(item) == 'radio'"" data-i-id=""'filter#{@id}'"" type=""radio"" data-i-name=""'filter_name#{@pid}'"" data-i-value=""'#{@index}'""/>          " + "\n";
            idxHtmlTemplate += @"         <label data-i-for=""'filter#{@id}'"" data-i-title=""item.display"" data-itext=""item.display"" data-class=""tag-parent: #{@itemkey}.children; checked: KEY_PROJECT_TAG_STATES#{@path}""></label>" + "\n";
            idxHtmlTemplate += @"         <ul class=""wFltOptsGrp"" data-child=""#{@itemkey}.children"" data-rif=""item.children""></ul>" + "\n";
            idxHtmlTemplate += @"       </li>" + "\n";
            idxHtmlTemplate += @"    </ul>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Sidebar sizer -->" + "\n";
            idxHtmlTemplate += @"<div class=""sidebarsizer left-pane boundry column-resize"" data-if=""@.l.desktop_sidebar_available === true"" data-resize=""@.l.desktop_sidebar_visible(@sidebar_width == null || @sidebar_width != '0px') | x: 'sidebar_width', maxx: 0.7, screen: 'desktop'"" data-css=""left: sidebar_width | screen: 'desktop', dir: 'ltr'; right: sidebar_width | screen: 'desktop', dir: 'rtl'"" data-class=""desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false;"">" + "\n";
            idxHtmlTemplate += @"   <a class=""sidebartoggle"" data-click=""@sidebar_width(null) | screen: 'desktop'"" data-toggle="".l.desktop_sidebar_visible"" data-attr=""title: @KEY_LNG.SidebarToggleTip"">&nbsp;</a>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Search field -->" + "\n";
            idxHtmlTemplate += @"<div class=""searchbar left-pane"" data-css=""width: sidebar_width | screen: 'desktop'"" data-class=""sidebar-opened: $mc.isSidebarTab(@KEY_ACTIVE_TAB); desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; mobile-header-visible: @.l.mobile_header_visible; searchpage-mode, layout-visible: @KEY_ACTIVE_TAB == 'fts'; search-sidebar: @KEY_SEARCH_LOCATION == 'tabbar'; searchbar-mobile:KEY_SCREEN_PHONE; search-content: @KEY_SEARCH_LOCATION == 'content';  @SEARCH_RESULTS_KEY!== undefined &&  (@SEARCH_RESULTS_KEY).length>0"" data-controller=""SearchController:sc"">" + "\n";
            idxHtmlTemplate += @"   <a class=""mobile_back"" data-click=""@KEY_ACTIVE_TAB(null)"" data-attr=""title: @KEY_LNG.Back""></a>" + "\n";
            idxHtmlTemplate += @"   <div class=""search-input"" data-class=""search-input-open:@focusin_main_searchbox && @SEARCH_RESULTS_KEY!== undefined &&  (@SEARCH_RESULTS_KEY).length>0"" data-if=""$mc.isSearchMode(@KEY_ACTIVE_TAB, @active_content)"">" + "\n";
            idxHtmlTemplate += @"       <input class=""wSearchField"" type=""text"" data-class=""no-filter: !@KEY_FEATURE.filter"" data-attr=""placeholder: @KEY_LNG.Search""/>" + "\n";
            idxHtmlTemplate += @"       <a class=""wSearchLink"" data-click=""@EVT_SEARCH_TERM(true)"" data-attr=""href: '#'"" data-if=""@KEY_SCREEN_PHONE"">&nbsp;</a>   " + "\n";
            idxHtmlTemplate += @"       <div data-if=""@focusin_main_searchbox && @SEARCH_RESULTS_KEY!== undefined &&  (@SEARCH_RESULTS_KEY).length>0"" class=""search-list"" >" + "\n";
            idxHtmlTemplate += @"         <table data-class=""search-table-desktop:KEY_SCREEN_DESKTOP; search-table-mobile:KEY_SCREEN_PHONE; search-table-tablet:KEY_SCREEN_TABLET"">" + "\n";
            idxHtmlTemplate += @"           <tr data-repeat=""search_results"" data-class=""search-suggestion:true; search-selected:@selected===#{@index}"" data-click=""$sc.handleClick(#{@index})"">" + "\n";
            idxHtmlTemplate += @"               <td class=""search-text-column""><div class=""search-text"" data-itext=""item.term""></div> </td>" + "\n";
            idxHtmlTemplate += @"               <td>" + "\n";
            idxHtmlTemplate += @"                   <div class=""search-delete"" data-if=""$sc.canDelete(#{@index})"" data-click=""$sc.handleDelete(#{@index})""></div>" + "\n";
            idxHtmlTemplate += @"                   </td>" + "\n";
            idxHtmlTemplate += @"           </tr>" + "\n";
            idxHtmlTemplate += @"         </table> " + "\n";
            idxHtmlTemplate += @"       </div>" + "\n";
            idxHtmlTemplate += @"   </div>  " + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Search results -->" + "\n";
            idxHtmlTemplate += @"<div class=""searchresults left-pane"" data-css=""width: sidebar_width | screen: 'desktop'; left: sidebar_width | screen: 'desktop', dir: 'ltr'; right: sidebar_width | screen: 'desktop', dir: 'rtl'"" data-class=""sidebar-opened: $mc.isSidebarTab(@KEY_ACTIVE_TAB); desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; search-sidebar: @KEY_SEARCH_LOCATION == 'tabbar'; search-content: @KEY_SEARCH_LOCATION == 'content'; layout-visible: $mc.isSearchMode(@KEY_ACTIVE_TAB, @active_content); mobile-header-visible: @.l.mobile_header_visible"" data-scroll=""@.l.load_more_results(true) | debounce: 50, delta: 100"">" + "\n";
            idxHtmlTemplate += @"   " + "\n";
            idxHtmlTemplate += @"   <div class=""wSearchResults"" id=""searchresults"">" + "\n";
            idxHtmlTemplate += @"       <div class=""wSearchResultSettings rh-hide"">" + "\n";
            idxHtmlTemplate += @"           <div class=""wSearchHighlight"">" + "\n";
            idxHtmlTemplate += @"               <input id=""highlightsearch"" type=""checkbox"" checked="""" class=""wSearchHighlight"" onclick=""onToggleHighlightSearch()"" />" + "\n";
            idxHtmlTemplate += @"           </div>" + "\n";
            idxHtmlTemplate += @"       </div>" + "\n";
            idxHtmlTemplate += @"       <div class=""wSearchMessage"" data-if=""!@EVT_SEARCH_IN_PROGRESS"">" + "\n";
            idxHtmlTemplate += @"           <span id=""searchMsg"" class=""wSearchMessage"">2つ以上の語句を入力して検索する場合は、スペース（空白）で区切ります。</span> " + "\n";
            idxHtmlTemplate += @"            " + "\n";
            idxHtmlTemplate += @"       </div>" + "\n";
            idxHtmlTemplate += @"       <div data-class=""loading: EVT_SEARCH_IN_PROGRESS"" data-if=""EVT_SEARCH_IN_PROGRESS""></div>" + "\n";
            idxHtmlTemplate += @"       <p class=""progressbar"" data-if=""KEY_SEARCH_PROGRESS""><span data-text=""KEY_SEARCH_PROGRESS""></span>%</p>" + "\n";
            idxHtmlTemplate += @"       <div class=""wSearchResultItemsBlock"" data-if=""!@EVT_SEARCH_IN_PROGRESS"">" + "\n";
            idxHtmlTemplate += @"           <div data-rhwidget=""List: key: @.p.searchresults, spliton: index % @MAX_RESULTS == 14"" data-config=""loadmore: '.l.load_more_results', loaded: '.l.results_loaded'"">" + "\n";
            idxHtmlTemplate += @"               <div class=""wSearchResultItem"">" + "\n";
            idxHtmlTemplate += @"                   <a class=""nolink"" data-i-href=""item.strUrl+@.p.searchresultparams"">" + "\n";
            idxHtmlTemplate += @"                       <div class=""wSearchResultTitle"" data-itext=""item.strTitle""></div>" + "\n";
            idxHtmlTemplate += @"                   </a>" + "\n";
            idxHtmlTemplate += @"                   <div class=""wSearchContent"">" + "\n";
            idxHtmlTemplate += @"                       <span class=""wSearchContext"" data-itext=""item.strSummary""></span>" + "\n";
            idxHtmlTemplate += @"                   </div>" + "\n";
            idxHtmlTemplate += @"                   <div class=""wSearchURL"">" + "\n";
            idxHtmlTemplate += @"                       <span class=""wSearchURL"" data-itext=""item.strBreadcrumbs""></span>" + "\n";
            idxHtmlTemplate += @"                   </div>" + "\n";
            idxHtmlTemplate += @"               </div>" + "\n";
            idxHtmlTemplate += @"           </div>" + "\n";
            idxHtmlTemplate += @"       </div>" + "\n";
            idxHtmlTemplate += @"       <div data-if=""@.p.searchresults.length && !@EVT_SEARCH_IN_PROGRESS"" class=""wSearchResultsEnd"">" + "\n";
            idxHtmlTemplate += @"           <span>検索結果の最後です。</span>" + "\n";
            idxHtmlTemplate += @"       </div>" + "\n";
            idxHtmlTemplate += @"   </div>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Topics -->" + "\n";
            idxHtmlTemplate += @"<div class=""topic main"" data-css=""left: sidebar_width | screen: 'desktop', dir: 'ltr'; right: sidebar_width | screen: 'desktop', dir: 'rtl'"" data-class=""sidebar-opened: $mc.isSidebarTab(@KEY_ACTIVE_TAB); desktop-sidebar-hidden: @.l.desktop_sidebar_visible == false || @.l.desktop_sidebar_available === false; mobile-header-visible: @.l.mobile_header_visible"">" + "\n";
            idxHtmlTemplate += @"   <div class=""functionholder"">" + "\n";
            idxHtmlTemplate += @"     <div class=""buttons"">" + "\n";
            idxHtmlTemplate += @"       <div class=""print_page"" id=""print_page"">" + "\n";
            idxHtmlTemplate += @"         <div class=""print_page_area"" title=""いま表示されているページをPDFとして保存します。""><img src=""./template/Azure_Blue01/icon_pdf.png""><p class=""print_page_title"">ページ印刷</p></div>" + "\n";
            idxHtmlTemplate += @"       </div>" + "\n";
            idxHtmlTemplate += @"       <p class=""fontchange_title"">文字サイズ</p>" + "\n";
            idxHtmlTemplate += @"       <div class=""fontsize_change"" id=""fontsize_small""><span>小</span></div>" + "\n";
            idxHtmlTemplate += @"       <div class=""fontsize_change"" id=""fontsize_medium""><span>中</span></div>" + "\n";
            idxHtmlTemplate += @"       <div class=""fontsize_change"" id=""fontsize_large""><span>大</span></div>" + "\n";
            idxHtmlTemplate += @"       <div class=""brs_previous"" data-attr=""title:@KEY_LNG.Prev""><a id=""browseSeqBack"" class=""wBSBackButton"" data-rhwidget=""Basic"" data-attr=""href:.l.brsBack"" data-css=""visibility: @.l.brsBack?'visible':'hidden'"">&nbsp;</a>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"       <div class=""brs_next"" data-attr=""title:@KEY_LNG.Next""><a id=""browseSeqNext"" class=""wBSNextButton"" data-rhwidget=""Basic"" data-attr=""href:.l.brsNext"" data-css=""visibility: @.l.brsNext?'visible':'hidden'"">&nbsp;</a>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"     </div>" + "\n";
            idxHtmlTemplate += @"   </div>" + "\n";
            idxHtmlTemplate += @"   <div class=""topic-state"" data-class=""loading: EVT_TOPIC_LOADING"" data-if=""EVT_TOPIC_LOADING""></div>" + "\n";
            idxHtmlTemplate += @"   <iframe class=""topic"" name=""rh_default_topic_frame_name""></iframe>" + "\n";
            idxHtmlTemplate += @"   <a class=""to_top"" data-trigger=""EVT_SCROLL_TO_TOP"" data-attr=""title:@KEY_LNG.ToTopTip"">&#160;</a> " + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Social media buttons -->" + "\n";
            idxHtmlTemplate += @"<div class=""social_buttons"" data-if=""@KEY_FEATURE.social === true && (@KEY_SCREEN_PHONE == false || (@KEY_SCREEN_PHONE == true && $mc.isSidebarTab(@KEY_ACTIVE_TAB) != true && $mc.isSearchMode(@KEY_ACTIVE_TAB, @active_content) != true && @KEY_ACTIVE_TAB != 'filter'))"" data-class=""opened: @.l.social_opened === true;"">" + "\n";
            idxHtmlTemplate += @"   <a class=""social_buttons_controller"" href=""javascript:rh.model.publish('l.social_opened', rh.model.get('l.social_opened') === true ? false : true)""></a>" + "\n";
            idxHtmlTemplate += @"   <div class=""fb-button"" data-if=""KEY_FEATURE.facebook""><iframe id=""bf-iframe"" style=""border:none; overflow:hidden;""></iframe></div>" + "\n";
            idxHtmlTemplate += @"   <div class=""twitter-button"" id=""twitter-holder"" data-if=""KEY_FEATURE.twitter""></div>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- pdf modal -->" + "\n";
            idxHtmlTemplate += @"<div id=""modalPdf"">" + "\n";
            idxHtmlTemplate += @"  <div id=""modalPdfContents"">" + "\n";
            idxHtmlTemplate += @"    <div id=""modalPdfContentsHeader"">" + "\n";
            idxHtmlTemplate += @"      <div id=""modalPdfContentsTitle"">PDF出力</div>" + "\n";
            idxHtmlTemplate += @"      <div id=""buttonCloseModalPdf""></div>" + "\n";
            idxHtmlTemplate += @"    </div>" + "\n";
            idxHtmlTemplate += @"    <div id=""modalPdfLoaderTitle"">PDFプレビュー</div>" + "\n";
            idxHtmlTemplate += @"    <div id=""modalPdfLoaderWrap"">" + "\n";
            idxHtmlTemplate += @"      <div id=""modalPdfLoaderLoading""></div>" + "\n";
            idxHtmlTemplate += @"      <div id=""modalPdfLoader""></div>" + "\n";
            idxHtmlTemplate += @"    </div>" + "\n";
            idxHtmlTemplate += @"    <div id=""modalPdfContentsFooter"">" + "\n";
            idxHtmlTemplate += @"      <div id=""modalPdfPager"">" + "\n";
            idxHtmlTemplate += @"        <div id=""modalPdfPagePrev"" class=""modalPdfPageButton off""></div>" + "\n";
            idxHtmlTemplate += @"        <div id=""modalPdfPage""><span id=""modalPdfPageCurrent"">-</span>/<span id=""modalPdfPageAll"">-</span>ページ</div>" + "\n";
            idxHtmlTemplate += @"        <div id=""modalPdfPageNext"" class=""modalPdfPageButton off""></div>" + "\n";
            idxHtmlTemplate += @"      </div>" + "\n";
            idxHtmlTemplate += @"      <ul id=""modalPdfButtons"">" + "\n";
            idxHtmlTemplate += @"        <li id=""buttonOutputPdf"">PDF出力</li>" + "\n";
            idxHtmlTemplate += @"        <li id=""buttonCancelPdf"">キャンセル</li>" + "\n";
            idxHtmlTemplate += @"      </ul>" + "\n";
            idxHtmlTemplate += @"    </div>" + "\n";
            idxHtmlTemplate += @"  </div>" + "\n";
            idxHtmlTemplate += @"  <div id=""modalPdfBg""></div>" + "\n";
            idxHtmlTemplate += @"</div>" + "\n";
            idxHtmlTemplate += @"<!-- Scripts -->" + "\n";
            idxHtmlTemplate += @"<script src=""template/Azure_Blue01/usersettings.js"" type=""text/javascript""></script>" + "\n";
            idxHtmlTemplate += @"<script>" + "\n";
            idxHtmlTemplate += @"if(useTwitter === true) {" + "\n";
            idxHtmlTemplate += @"   !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');" + "\n";
            idxHtmlTemplate += @"}" + "\n";
            idxHtmlTemplate += @"</script>" + "\n";
            //idxHtmlTemplate += @"<script type=""text/javascript"" src=""whxdata/whtagdata.js""></script>" + "\n";
            idxHtmlTemplate += @"</body>" + "\n";
            idxHtmlTemplate += @"</html>" + "\n";
            return idxHtmlTemplate;
        }
    }
}
